name: user_app
description: Ride sharing user app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  dio: ^5.7.0
  change_app_package_name: ^1.4.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.4
  fluttertoast: ^8.2.10
  video_player: ^2.9.2
  cached_network_image: ^3.4.1
  rename_app: ^1.6.1
  intl: ^0.20.1
  file_picker: ^6.1.1
  flutter_screenutil: ^5.9.3
  go_router: ^14.6.3
  url_launcher: ^6.2.5
  device_info_plus: ^9.1.2
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  flutter_markdown: ^0.6.18
  flutter_html: ^3.0.0-beta.2
  flutter_animate: ^4.5.2
  skeletonizer: ^1.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  freezed: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    # Comment out images until you add some
    # - assets/images/
